#!/bin/bash
restorelog="/var/log/restoreboot.log"
echo "restoreboot $(date) $USER" >> "$restorelog"

### Enable lockscreen ###
_stock=$(awk NR==1 "/opt/justbrowsing/stock");
echo -e "$_stock\n$_stock" | passwd user 2>&1 | tee -a "$restorelog"

# Load from config file
rm /etc/justbrowsing/data/config 2>&1 | tee -a "$restorelog"
loadjb-config 2>&1 | tee -a "$restorelog"
setjb-gpu load 2>&1 | tee -a "$restorelog"
setjb-clean load 2>&1 | tee -a "$restorelog"
setjb-printers load 2>&1 | tee -a "$restorelog"
systemctl start savejb-daemon 2>&1 | tee -a "$restorelog"
